name: Deploy Test API

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted,frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check the current user
        run: |
          whoami

      - name: Build Frontend API Docker image
        run: |
          docker build -t frontend_api_image .

      - name: Deploy Frontend API
        run: |
          docker stop frontend_api_container || true
          docker rm frontend_api_container || true
          docker run -d \
          -e PORT=${{vars.API_PORT}} \
          -e NODE_ENV=${{vars.API_NODE_ENV}} \
          -e MONGO_URI=${{secrets.MONGO_URI}} \
          -e JWT_SECRET=${{secrets.JWT_SECRET}} \
          -e GMAIL_USERNAME=${{secrets.GMAIL_USERNAME}} \
          -e GMAIL_PASSWORD=${{secrets.GMAIL_PASSWORD}} \
          --name frontend_api_container \
          -p ${{vars.PORT}}:${{vars.PORT}} \
          frontend_api_image:latest

      - name: Remove Dangling Docker images
        run: |
          docker rmi $(docker images --quiet --filter "dangling=true") || true
